---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominik
  namespace: praxe2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dominik
  template:
    metadata:
      labels:
        app: dominik
    spec:
      containers:
        - name: demo
          image: ghcr.io/dominik-3/praxe-demo67:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dominik
  namespace: praxe2026
spec:
  selector:
    app: dominik
  ports:
    - port: 80
      targetPort: 8080
