---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakub-frontend
  namespace: praxe2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakub-frontend
  template:
    metadata:
      labels:
        app: jakub-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/praxe-demo12-frontend:latest
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: jakub-frontend
  namespace: praxe2026
spec:
  selector:
    app: jakub-frontend
  ports:
    - port: 80
      targetPort: 4200
