---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: praxe-user-1-binding
  namespace: praxe2026
subjects:
  - kind: ServiceAccount
    name: praxe-user-1
    namespace: praxe2026
roleRef:
  kind: Role
  name: praxe2026-developer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: praxe-user-2-binding
  namespace: praxe2026
subjects:
  - kind: ServiceAccount
    name: praxe-user-2
    namespace: praxe2026
roleRef:
  kind: Role
  name: praxe2026-developer
  apiGroup: rbac.authorization.k8s.io
