# Kubernetes 1.24+ nevytváří tokeny pro ServiceAccount automaticky.
# Tento Secret typ "service-account-token" vytvoří trvalý token.
---
apiVersion: v1
kind: Secret
metadata:
  name: praxe-user-1-token
  namespace: praxe2026
  annotations:
    kubernetes.io/service-account.name: praxe-user-1
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: praxe-user-2-token
  namespace: praxe2026
  annotations:
    kubernetes.io/service-account.name: praxe-user-2
type: kubernetes.io/service-account-token
