apiVersion: v1
kind: ResourceQuota
metadata:
  name: praxe2026-quota
  namespace: praxe2026
spec:
  hard:
    # CPU
    requests.cpu: "10"
    limits.cpu: "10"
    # RAM
    requests.memory: 20Gi
    limits.memory: 20Gi
    # Počet objektů
    pods: "50"
    services: "20"
    persistentvolumeclaims: "10"
    secrets: "30"
    configmaps: "30"
