services:
  mysql:
    image: mysql:8.4
    container_name: demo6-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: RootPass1!
      MYSQL_DATABASE: demo6db
      MYSQL_USER: demo6admin
      MYSQL_PASSWORD: Demo6Pass1!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "demo6admin", "-pDemo6Pass1!"]
      interval: 10s
      timeout: 5s
      retries: 5

  maven:
    image: maven:3.9-eclipse-temurin-21
    container_name: demo-maven
    working_dir: /app
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    ports:
      - "8080:8080"
    command: mvn -version



  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "9111:9111"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/demo6db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: demo6admin
      SPRING_DATASOURCE_PASSWORD: Demo6Pass1!
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"


  backend-dev:
    image: maven:3.9-eclipse-temurin-21
    container_name: spring-backend-dev
    working_dir: /app
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    ports:
      - "9111:9111"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/demo6db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: demo6admin
      SPRING_DATASOURCE_PASSWORD: Demo6Pass1!
    depends_on:
      mysql:
        condition: service_healthy
    command: mvn spring-boot:run

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0
    depends_on:
      - backend-dev

volumes:
  maven-repo:
  mysql-data: