apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dominik
  namespace: argocd
spec:
  project: mentors
  source:
    repoURL: "https://github.com/claivent/demo6.git"
    targetRevision: master
    path: __demo6-gitops/argocd-deploy-kustomization/
    kustomize:
      patches: []
  destination:
    server: https://kubernetes.default.svc
    namespace: mentors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
