apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - step01-namespace.yaml
  - mentor-backend-deploy.yaml
  - mentor-frontend-deploy.yaml
 
images:
  - name: ghcr.io/claivent/demo6-backend
    newTag: "b67b439"
  - name: ghcr.io/claivent/demo6-frontend
    newTag: "3102cbe"

patches:
  - path: patch-env.yaml
    