apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - step01-namespace.yaml
  - mentor-backend-deploy.yaml
  - mentor-frontend-deploy.yaml
  - mysql/mysql-secret.yaml
  - mysql/mysql-pvc.yaml
  - mysql/mysql-configmap.yaml
  - mysql/mysql-deploy.yaml

images:
  - name: ghcr.io/claivent/demo6-backend
    newTag: "9a4193a"
  - name: ghcr.io/claivent/demo6-frontend
    newTag: "3102cbe"

patches:
  - path: patch-env.yaml
    