apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentor
  namespace: mentors
spec:
  template:
    spec:
      containers:
        - name: demo
          env:
            - name: APP_VERSION
              value: "2c17958"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mentor-mysql:3306/demo6db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password